=== c-arianna/library-microservices/contracts/src/main/resources/contracts/book/book.reserved/v1/event.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "BookReservedEventV1",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"eventId": {
			"type": "string",
			"format": "uuid"
		},
		"eventType": {
			"type": "string",
			"const": "BOOK_RESERVED"
		},
		"producer": {
			"type": "string",
			"const": "book-service"
		},
		"aggregateId": {
			"type": "string"
		},
		"aggregateType": {
			"type": "string",
			"const": "BOOK"
		},
		"eventVersion": {
			"type": "integer"
		},
		"occurredAt": {
			"type": "string",
			"format": "date-time"
		},
		"schemaVersion": {
			"type": "integer",
			"const": 1
		},
		"payload": {
			"properties": {
				"isbn": {
					"type": "string"
				},
				"loanId": {
					"type": "string"
				},
				"userId": {
					"type": "string"
				}
			},
			"required": [
				"isbn",
				"loanId",
				"userId"
			]
		}
	},
	"required": [
		"eventId",
		"eventType",
		"producer",
		"aggregateId",
		"aggregateType",
		"eventVersion",
		"occurredAt",
		"schemaVersion",
		"payload"
	]
}

=== c-arianna/library-microservices/contracts/src/main/resources/contracts/book/book.reserved/v1/sample.json
{
  "eventId": "10c1f3cd-0a10-42fe-b1d4-15864beb27e4",
  "eventType": "BOOK_RESERVED",
  "producer": "book-service",
  "aggregateId": "9788828606819",
  "aggregateType": "BOOK",
  "eventVersion": 0,
  "occurredAt": "2026-06-09T14:40:00Z",
  "schemaVersion": 1,

  "payload": {
    "isbn": "9788828606819",
    "loanId": "4b659787-bc8d-481a-86ca-b5d8dbc37e70",
    "userId": "77230652-e993-41e4-a8b1-7bba476a08e6"
  }
}
