=== c-arianna/library-microservices/contracts/src/main/resources/contracts/user/user.suspended/V1/event.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "UserSuspendEventV1",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"eventId": {
			"type": "string",
			"format": "uuid"
		},
		"eventType": {
			"type": "string",
			"const": "USER_SUSPENDED"
		},
		"producer": {
			"type": "string",
			"const": "user-service"
		},
		"aggregateId": {
			"type": "string"
		},
		"occurredAt": {
			"type": "string",
			"format": "date-time"
		},
		"schemaVersion": {
			"type": "integer",
			"const": 1
		},
		"payload": {
			"properties": {
				"userId": {
					"type": "string"
				},
				"status": {
					"type": "string",
					"const": "SUSPENDED"
				}
			},
			"required": [
				"userId",
				"status"
			]
		}
	},
	"required": [
		"eventId",
		"eventType",
		"producer",
		"aggregateId",
		"occurredAt",
		"schemaVersion",
		"payload"
	]
}

=== c-arianna/library-microservices/contracts/src/main/resources/contracts/user/user.suspended/V1/sample.json
{
  "eventId": "f21d7bd7-4fca-4373-9ff0-c3359b4ee0d2",
  "eventType": "USER_SUSPENDED",
  "producer": "user-service",
  "aggregateId": "3ad089a7-64b1-49b4-9fbc-7278be2b939b",
  "occurredAt": "2026-06-10T12:45:00Z",
  "schemaVersion": 1,

  "payload": {
    "userId": "3ad089a7-64b1-49b4-9fbc-7278be2b939b",
    "status": "SUSPENDED"
  }
}
